### ISSUE TITLE
Fehlende Einträge in BibTex-Datei

### ISSUE THREAD

**Issue by ablaette** [ablaette/JointSessions2023#1]
Die letzten beiden Einträge dieser Klammer ...

[@petrocik_issue_2003; @brug_issue_2004; @esteve_del_valle_political_2021; @gilardi_issue_2021; @walgrave_associative_2012; @walgrave_where_2007; @lefevere2020; @tresch2018]

sind nicht in Isa's references.bib in Google Drive. Resultiert beim rendern des qmd in:

[WARNING] Citeproc: citation lefevere2020 not found
[WARNING] Citeproc: citation tresch2018 not found

**Comment by isaborucki** [comment]
solved, habe die fehlenden Einträge in .bib ergänzt.
